require("dotenv").config();
const express=require("express"),cors=require("cors"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),Database=require("better-sqlite3");
const app=express(),db=new Database("gyanova.sqlite");
app.use(helmet());app.use(express.json({limit:"2mb"}));app.use(cors({origin:process.env.CORS_ORIGIN||true}));app.use(rateLimit({windowMs:15*60*1000,max:300}));
db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE,password_hash TEXT);CREATE TABLE IF NOT EXISTS videos(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,category TEXT,url TEXT,description TEXT,thumbnail TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS announcements(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,body TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS tests(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,subject TEXT,questions_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(process.env.OWNER_EMAIL&&process.env.OWNER_PASSWORD&&!db.prepare("SELECT id FROM admins WHERE email=?").get(process.env.OWNER_EMAIL))db.prepare("INSERT INTO admins(email,password_hash) VALUES(?,?)").run(process.env.OWNER_EMAIL,bcrypt.hashSync(process.env.OWNER_PASSWORD,12));
function auth(req,res,next){try{const h=req.headers.authorization||"";req.admin=jwt.verify(h.replace("Bearer ",""),process.env.JWT_SECRET);next()}catch(e){res.status(401).json({error:"Unauthorized"})}}
function yt(u){try{const x=new URL(u);return ["youtube.com","www.youtube.com","youtu.be","youtube-nocookie.com"].includes(x.hostname)}catch{return false}}
app.get("/api/health",(q,s)=>s.json({ok:true,name:"GYANOVA"}));
app.post("/api/admin/login",rateLimit({windowMs:600000,max:10}),(q,s)=>{const {email,password}=q.body||{},a=db.prepare("SELECT * FROM admins WHERE email=?").get(email);if(!a||!bcrypt.compareSync(password||"",a.password_hash))return s.status(401).json({error:"Invalid login"});s.json({token:jwt.sign({id:a.id,email:a.email},process.env.JWT_SECRET,{expiresIn:"8h"})})});
app.get("/api/videos",(q,s)=>s.json(db.prepare("SELECT * FROM videos ORDER BY id DESC").all()));
app.post("/api/admin/videos",auth,(q,s)=>{const {title,category,url,description="",thumbnail=""}=q.body||{};if(!title||!category||!url||!yt(url))return s.status(400).json({error:"Valid YouTube URL required"});const r=db.prepare("INSERT INTO videos(title,category,url,description,thumbnail) VALUES(?,?,?,?,?)").run(title,category,url,description,thumbnail);s.status(201).json(db.prepare("SELECT * FROM videos WHERE id=?").get(r.lastInsertRowid))});
app.delete("/api/admin/videos/:id",auth,(q,s)=>{db.prepare("DELETE FROM videos WHERE id=?").run(q.params.id);s.json({ok:true})});
app.get("/api/announcements",(q,s)=>s.json(db.prepare("SELECT * FROM announcements ORDER BY id DESC").all()));
app.post("/api/admin/announcements",auth,(q,s)=>{const {title,body}=q.body||{};if(!title||!body)return s.status(400).json({error:"Title and body required"});const r=db.prepare("INSERT INTO announcements(title,body) VALUES(?,?)").run(title,body);s.status(201).json({id:r.lastInsertRowid})});
app.get("/api/tests",(q,s)=>s.json(db.prepare("SELECT id,title,subject,created_at FROM tests ORDER BY id DESC").all()));
app.post("/api/admin/tests",auth,(q,s)=>{const {title,subject,questions=[]}=q.body||{};if(!title||!subject)return s.status(400).json({error:"Title and subject required"});const r=db.prepare("INSERT INTO tests(title,subject,questions_json) VALUES(?,?,?)").run(title,subject,JSON.stringify(questions));s.status(201).json({id:r.lastInsertRowid})});
app.get("/api/admin/stats",auth,(q,s)=>s.json({videos:db.prepare("SELECT count(*) c FROM videos").get().c,announcements:db.prepare("SELECT count(*) c FROM announcements").get().c,tests:db.prepare("SELECT count(*) c FROM tests").get().c}));
app.post("/api/ai/explain",(q,s)=>{if(!process.env.AI_API_KEY)return s.status(503).json({error:"AI provider is not configured. Add AI_API_KEY on the server."});s.status(501).json({error:"Connect your selected AI provider in this endpoint before launch."})});
app.listen(process.env.PORT||8080,()=>console.log("GYANOVA API running"));
